import { signIn, signOut, useSession } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"

import { api } from "~/utils/api"
import styles from "./index.module.css"
import { Button } from "@mantine/core"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Button> Hello World</Button>
      </main>
    </>
  )
}
