import Head from "next/head"

import { useDisclosure } from "@mantine/hooks"
import { AppShell, Burger, Button } from "@mantine/core"

export default function Home() {
  const [opened, { toggle }] = useDisclosure()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Button> Hello World</Button> */}
        <AppShell
          header={{ height: 60 }}
          navbar={{
            width: 300,
            breakpoint: "sm",
            collapsed: { mobile: !opened },
          }}
          padding="md"
        >
          <AppShell.Header>
            <Burger
              opened={opened}
              onClick={toggle}
              hiddenFrom="sm"
              size="sm"
            />
            <div>Logo</div>
          </AppShell.Header>

          <AppShell.Navbar p="md">Navbar</AppShell.Navbar>

          <AppShell.Main>Main</AppShell.Main>
        </AppShell>
        );
      </main>
    </>
  )
}
